# -*- coding: utf-8 -*-
"""01_lr -Homework1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiWfaWd5rhTRE8T4Imhyc-1DrKLRUkA6

# Homework 01 — Linear Regression from scratch

Fit `y = b0 + b1*x1 + b2*x2` using batch gradient descent, written by hand.
No scikit-learn, no statsmodels — the point is to see every step.

Why gradient descent when a closed form exists? Because the closed form only
works for linear regression. The loop here is the same loop that trains
logistic regression and every neural network. We fit both ways and compare —
that comparison is the correctness check.

**Both blanks are filled in below:**
1. `gradient()` — differentiate the loss
2. `fit_gradient_descent()` — the loop that repeatedly calls it
"""

import numpy as np

SEED = 676
N_SAMPLES = 200
TRUE_INTERCEPT = 3.0
TRUE_COEFS = np.array([2.5, -1.2])
NOISE_SD = 1.5

LEARNING_RATE = 0.05
N_ITERATIONS = 2000

"""## 1. Toy data"""

def make_data(rng):
    """
    Build a small regression dataset with a known answer.

    Because we choose the true coefficients ourselves, we can check whether the
    fitting loop recovered them. Real data never gives you that luxury, which is
    exactly why toy data is the right place to learn the algorithm.
    """
    X = rng.normal(loc=0.0, scale=1.0, size=(N_SAMPLES, 2))
    noise = rng.normal(loc=0.0, scale=NOISE_SD, size=N_SAMPLES)
    y = TRUE_INTERCEPT + X @ TRUE_COEFS + noise
    return X, y


def add_intercept(X):
    """Prepend a column of ones so the intercept is just another coefficient."""
    return np.hstack([np.ones((X.shape[0], 1)), X])

"""## 2. The pieces of the model"""

def predict(X_design, beta):
    """yhat = X @ beta. One matrix multiply is the whole forward pass."""
    return X_design @ beta


def mse(y_true, y_pred):
    """Mean squared error — the loss we are minimising."""
    return float(np.mean((y_true - y_pred) ** 2))

"""### `gradient()` — filled in

The loss is `L(beta) = (1/n) * sum_i (y_i - x_i . beta)^2`. Let
`residual = y - X @ beta`. Differentiating (chain rule on the square, then
`d/dbeta (x_i . beta) = x_i`) gives

```
dL/dbeta = -(2/n) * X.T @ residual
```

Sign matters: it's *negative* because increasing beta shrinks the residual,
which shrinks the loss.
"""

def gradient(X_design, y, beta):
    """
    Gradient of the MSE with respect to beta.

    :return: array with the SAME shape as beta — one partial derivative per
             coefficient, telling you which way each one should move.
    """
    n = X_design.shape[0]
    residual = y - X_design @ beta
    return -(2.0 / n) * (X_design.T @ residual)


def normal_equation(X_design, y):
    """
    Closed-form least squares: beta = (X'X)^-1 X'y.

    This is the exact answer. We use it only to check the loop — pinv is used
    instead of inv so a singular X'X does not blow up.
    """
    return np.linalg.pinv(X_design.T @ X_design) @ X_design.T @ y

"""## 3. Fitting

### `fit_gradient_descent()` — filled in

Each iteration: predict, record the loss, compute the gradient at the
*current* beta, then step `beta -= lr * grad` — all coefficients at once.
"""

def fit_gradient_descent(X_design, y, lr=LEARNING_RATE, n_iter=N_ITERATIONS):
    """
    Fit beta by batch gradient descent.

    :return: (beta, history) where history is the loss at each iteration.
    """
    beta = np.zeros(X_design.shape[1])
    history = []

    for _ in range(n_iter):
        y_pred = predict(X_design, beta)
        history.append(mse(y, y_pred))
        grad = gradient(X_design, y, beta)
        beta = beta - lr * grad

    return beta, history

"""## 4. Run the fit"""

rng = np.random.default_rng(SEED)
X, y = make_data(rng)
X_design = add_intercept(X)

beta_gd, history = fit_gradient_descent(X_design, y)
beta_cf = normal_equation(X_design, y)
y_pred = predict(X_design, beta_gd)

beta_gd, beta_cf

"""## 5. Reporting"""

def r_squared(y_true, y_pred):
    """Fraction of variance explained. 1.0 is perfect, 0.0 is no better than the mean."""
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    return float(1 - ss_res / ss_tot)


def report(beta_gd, beta_cf, history, y, y_pred):
    print("=" * 62)
    print("  LINEAR REGRESSION — gradient descent vs closed form")
    print("=" * 62)
    names = ["intercept", "x1 coef", "x2 coef"]
    truth = [TRUE_INTERCEPT, *TRUE_COEFS]
    print(f"\n  {'':<12}{'true':>10}{'gradient':>12}{'closed form':>14}{'gap':>9}")
    for i, name in enumerate(names):
        gap = abs(beta_gd[i] - beta_cf[i])
        print(f"  {name:<12}{truth[i]:>10.4f}{beta_gd[i]:>12.4f}{beta_cf[i]:>14.4f}{gap:>9.5f}")

    print(f"\n  iterations run     : {len(history)}")
    print(f"  loss, first iter   : {history[0]:.4f}")
    print(f"  loss, last iter    : {history[-1]:.4f}")
    print(f"  MSE  (final)       : {mse(y, y_pred):.4f}")
    print(f"  R^2  (final)       : {r_squared(y, y_pred):.4f}")
    print(f"  noise floor (sd^2) : {NOISE_SD ** 2:.4f}   <- MSE cannot beat this")

    gap = float(np.max(np.abs(beta_gd - beta_cf)))
    verdict = "PASS" if gap < 0.01 else "TOO FAR APART — check the loop"
    print(f"\n  max gap vs closed form: {gap:.6f}   [{verdict}]")
    print("=" * 62)
    return gap

gap = report(beta_gd, beta_cf, history, y, y_pred)

"""## 6. Plot: fit and loss curve"""

import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))
order = np.argsort(X[:, 0])
ax1.scatter(X[:, 0], y, s=16, alpha=0.55, label="observed")
ax1.plot(X[order, 0], predict(add_intercept(X), beta_gd)[order], lw=2, color="crimson",
         label="fitted")
ax1.set_xlabel("x1"); ax1.set_ylabel("y"); ax1.set_title("Fit (vs x1)"); ax1.legend()

ax2.plot(history, lw=1.6)
ax2.set_xlabel("iteration"); ax2.set_ylabel("MSE"); ax2.set_yscale("log")
ax2.set_title("Loss curve")

fig.tight_layout()
plt.show()

"""## Reading the numbers

The MSE settles near the noise variance (1.5² = 2.25) — no model can do
better than that on this data, since the remaining error is the injected
noise itself, not a modelling failure.

The gradient-descent and closed-form coefficients agree to a very small gap
(well under 0.01), confirming the hand-written loop is finding the same
optimum as the exact linear-algebra solution.
"""